### ISSUE TITLE
[ERROR] toDate

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1392]
```text
Error
@emjpm/app:     at toDate (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/date-fns/toDate/index.js:55:20)
@emjpm/app:     at compareDesc (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/date-fns/compareDesc/index.js:54:38)
@emjpm/app:     at Array.sort (native)
@emjpm/app:     at newestLastLogin (/Users/tglatt/dev/git-repos/socialgouv/emjpm/packages/app/.next/server/static/development/pages/magistrats/gestionnaires/[gestionnaire_id].js:12720:26)
@emjpm/app:     at formatMandataire (/Users/tglatt/dev/git-repos/socialgouv/emjpm/packages/app/.next/server/static/development/pages/magistrats/gestionnaires/[gestionnaire_id].js:12743:81)
@emjpm/app:     at formatGestionnaire (/Users/tglatt/dev/git-repos/socialgouv/emjpm/packages/app/.next/server/static/development/pages/magistrats/gestionnaires/[gestionnaire_id].js:9107:100)
@emjpm/app:     at MagistratMandataire (/Users/tglatt/dev/git-repos/socialgouv/emjpm/packages/app/.next/server/static/development/pages/magistrats/gestionnaires/[gestionnaire_id].js:8577:97)
@emjpm/app:     at processChild (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
@emjpm/app:     at resolve (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
@emjpm/app:     at ReactDOMServerRenderer.render (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
@emjpm/app:     at ReactDOMServerRenderer.read (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
@emjpm/app:     at renderToString (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
@emjpm/app:     at render (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/next/dist/next-server/server/render.js:82:16)
@emjpm/app:     at Object.renderPage (/Users/tglatt/dev/git-repos/socialgouv/emjpm/node_modules/next/dist/next-server/server/render.js:332:20)
@emjpm/app:     at /Users/tglatt/dev/git-repos/socialgouv/emjpm/packages/app/.next/server/static/development/pages/_document.js:4358:21
```

**Comment by tglatt** [comment]
fix
